import Foundation
import Testing
@testable import Day7

struct Day7ExampleTests {

    @Test func exampleOne() {
        let input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """

        let parseResult = InputParser(input: input).parse()
        let result = Day7(input: parseResult).part1()

        #expect(result == 21)
    }

    @Test func examplePart2() {
        let input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """

        let parseResult = InputParser(input: input).parse()
        let result = Day7(input: parseResult).part2()

        #expect(result == 40)
    }
}
